-- MySQL Script generated by MySQL Workbench
-- Tue Oct 13 13:55:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema willSmithDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema willSmithDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `willSmithDatabase` DEFAULT CHARACTER SET utf8 ;
USE `willSmithDatabase` ;

-- -----------------------------------------------------
-- Table `willSmithDatabase`.`Anunciante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `willSmithDatabase`.`Anunciante` (
  `idAnunciante` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAnunciante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `willSmithDatabase`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `willSmithDatabase`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `numero` INT NOT NULL,
  `cep` VARCHAR(9) NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `willSmithDatabase`.`Imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `willSmithDatabase`.`Imovel` (
  `idImovel` INT NOT NULL AUTO_INCREMENT,
  `disponibilidade` VARCHAR(50) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `area` DOUBLE NULL,
  `quartos` INT NULL,
  `vagas` INT NULL,
  `banheiros` INT NULL,
  `descricao` VARCHAR(255) NULL,
  `Endereco_idEndereco` INT NOT NULL,
  `Anunciante_idAnunciante` INT NOT NULL,
  PRIMARY KEY (`idImovel`),
  INDEX `fk_Imovel_Endereco_idx` (`Endereco_idEndereco` ASC) VISIBLE,
  INDEX `fk_Imovel_Anunciante1_idx` (`Anunciante_idAnunciante` ASC) VISIBLE,
  CONSTRAINT `fk_Imovel_Endereco`
    FOREIGN KEY (`Endereco_idEndereco`)
    REFERENCES `willSmithDatabase`.`Endereco` (`idEndereco`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Imovel_Anunciante1`
    FOREIGN KEY (`Anunciante_idAnunciante`)
    REFERENCES `willSmithDatabase`.`Anunciante` (`idAnunciante`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `willSmithDatabase`.`Foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `willSmithDatabase`.`Foto` (
  `idFoto` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NOT NULL,
  `Imovel_idImovel` INT NOT NULL,
  PRIMARY KEY (`idFoto`),
  INDEX `fk_Foto_Imovel1_idx` (`Imovel_idImovel` ASC) VISIBLE,
  CONSTRAINT `fk_Foto_Imovel1`
    FOREIGN KEY (`Imovel_idImovel`)
    REFERENCES `willSmithDatabase`.`Imovel` (`idImovel`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
